### ISSUE TITLE
Cannot start - [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by nconder** [Tapawingo/FreeTakServer#47]
Application fails to start do to  [Errno -3] Temporary failure in name resolution. My DNS resolution (1.1.1.1) is functioning fine.

Running:
python3 /TAKlib/TAKfreeServer/server.py -p 8087

Output
# python3 /TAKlib/TAKfreeServer/server.py -p 8087
Traceback (most recent call last):
  File "/TAKlib/TAKfreeServer/server.py", line 350, in <module>
    ThreadedServer(host=const.IP, port=port).listen()
  File "/TAKlib/TAKfreeServer/server.py", line 64, in __init__
    self.sock.bind((self.host, self.port))
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by a-f-G-U-C** [comment]
The "name resolution" error is caused by a default placeholder line in constants.py:
https://github.com/Tapawingo/FreeTakServer/blob/242dab254e83bae1a2aa707a00a4a643803e433e/TAKfreeServer/constants.py#L15
You need to edit the file and replace the "Your IP" text with the IP address of your machine, alternatively set it to "0.0.0.0" which means "listen on all configured IP addresses of the local machine"

Note to @Tapawingo and devs, for OOTB functionality it might make sense to use 0.0.0.0 as default.

**Comment by nconder** [comment]
@a-f-G-U-C thanks adding the self.IP of 0.0.0.0 worked as expected.

**Comment by naman108** [comment]
actually it needs to be set to you're ip as opposed to 0.0.0.0 for DataPackages to work
